### ISSUE TITLE
.epk file identification

### ISSUE THREAD

**Issue by typelumina** [kurikomoe/FSNr_tools#2]
Hello, I extracted all the .epk files (more than 700) in the locale > us folder of the game and they all have a string of mixed numbers and letters per name. Is there any way to identify which chapter/day they belong to, or a way to organize them, other than opening each of them and checking the $$$message_0002_0003_0000$$$ string?

Thank you in advance!

**Comment by kurikomoe** [comment]
the [hash].epk is associated with a [name].ks,  `hash = some_hash_func(name)` (you can check that in script folder, there is a python script can give some hints)
>  Credit to @ Tea (not on github but discord), I was just tired of de-obfs that part of code.

And you may find out that the [name].ks is just some krkr scripts, with stringsreplaced by "message_xx_xx_xxx"

So, hash => name? No. You need to go though all [name].ks to build a lookup index and find the [hash].epk in reverse order.

**Comment by typelumina** [comment]
Thank you. If I may ask, where is the translation of the prologue stored? Because I've gone through the .epk files in that folder and it isn't there, I know there's a .fcf prologue file but it's under the kag folder. Where would the English translation be?

**Comment by kurikomoe** [comment]
root#data#locale#ck#epk#1jftmqc2rr04kclvl0ql71s2ef.epk

You mean this? Under Repo/example/ (chinese ver)

**Comment by typelumina** [comment]
OH thank you so much!!
